import type { NextPage } from "next";
import Head from "next/head";
import { Grid } from "@mui/material";
import { Fragment } from "react";

import { Card } from "./components";
import * as api from "../../api";

const Home: NextPage = () => {
  return (
    <Fragment>
      <Head>
        <title>Canary Bird Tech</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Grid
        container
        spacing={2}
        justifyContent="center"
        alignItems="flex-start"
      >
        {api.fetchProjects().map((project) => (
          <Grid item key={project.title}>
            <Card.CustomCard data={project} />
          </Grid>
        ))}
      </Grid>
    </Fragment>
  );
};

export default Home;

// Styled Components
