import type { NextPage } from "next";
import Head from "next/head";

import { Grid } from "@mui/material";
import { Fragment } from "react";
import { Card } from "./components";

const Home: NextPage = () => {
  return (
    <Fragment>
      <Head>
        <title>Canary Bird Tech</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Grid
        container
        spacing={2}
        justifyContent="center"
        alignItems="flex-start"
      >
        {getProjects().map(
          ({
            title,
            webUrl,
            originalWebUrl,
            summaryText,
            githubUrl,
            imageUrl,
            sonarUrl,
            sonarImageUrl,
            technologies,
          }) => (
            <Grid item key={title}>
              <Card.CustomCard
                {...{
                  title,
                  webUrl,
                  originalWebUrl,
                  summaryText,
                  githubUrl,
                  imageUrl,
                  sonarUrl,
                  sonarImageUrl,
                  technologies,
                }}
              />
            </Grid>
          )
        )}
      </Grid>
    </Fragment>
  );
};

function getProjects(): Card.CustomCardProps[] {
  return [
    {
      title: "SimplyWall.St Clone",
      webUrl: "https://simplywallst-clone.vercel.app",
      originalWebUrl: "https://simplywall.st",
      imageUrl: "/stock.jpg",
      githubUrl: "https://github.com/jonattfin/simplywallst-clone",
      sonarUrl:
        "https://sonarcloud.io/summary/new_code?id=jonattfin_simplywallst-clone",
      sonarImageUrl:
        "https://sonarcloud.io/api/project_badges/measure?project=jonattfin_simplywallst-clone&metric=alert_status",
      summaryText:
        "At Simply Wall St, our mission is to empower every retail investor in the world to make the best decisions possible.",
      technologies: [
        "https://nextjs.org",
        "https://storybook.js.org",
        "https://mui.com",
        "https://nivo.rocks",
        "https://react-query-v3.tanstack.com",
      ],
    },
    {
      title: "Ecosia.org Clone",
      webUrl: "https://ecosia-clone.vercel.app",
      originalWebUrl: "https://ecosia.org",
      imageUrl: "/spiderweb.jpg",
      githubUrl: "https://github.com/jonattfin/ecosia-clone-web",
      sonarUrl:
        "https://sonarcloud.io/summary/new_code?id=jonattfin_simplywallst-clone",
      sonarImageUrl:
        "https://sonarcloud.io/api/project_badges/measure?project=jonattfin_simplywallst-clone&metric=alert_status",
      summaryText: `Ecosia is a search engine based in Berlin, Germany. It donates 100% of its revenue to nonprofit organizations focusing on reforestation. 
        Ecosia considers itself a social business, claiming to be CO2-negative, and supports full financial transparency and protects the privacy of its users.`,
      technologies: [
        "https://nextjs.org",
        "https://storybook.js.org",
        "https://rxjs.dev",
        "https://mui.com",
        "https://nivo.rocks",
        "https://react-query-v3.tanstack.com",
      ],
    },
    {
      title: "Pulse.eco Clone",
      webUrl: "https://www.canarybird.io",
      originalWebUrl: "https://pulse.eco",
      imageUrl: "/iot.jpg",
      githubUrl: "https://github.com/jonattfin/canarybird-web",
      sonarUrl:
        "https://sonarcloud.io/summary/new_code?id=jonattfin_simplywallst-clone",
      sonarImageUrl:
        "https://sonarcloud.io/api/project_badges/measure?project=jonattfin_simplywallst-clone&metric=alert_status",
      summaryText: `Pulse.eco is a crowdsourcing platform, which gathers and presents environmental data. Our network of sensor installations and other third-party sources gathers the data and translates them into visual and easy to understand information.`,
      technologies: [
        "https://nextjs.org",
        "https://mui.com",
        "https://react-leaflet.js.org",
        "https://nivo.rocks",
        "https://react-query-v3.tanstack.com",
      ],
    },
  ];
}

export default Home;

// Styled Components
